# SPDX-FileCopyrightText: Digg
#
# SPDX-License-Identifier: CC0-1.0
---
name: MegaLinter
on: [workflow_call] # yamllint disable-line rule:truthy

env:
  MEGALINTER_CONFIG: /development/mega-linter.yml
jobs:
  megalinter:
    name: megalint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

        with:
          fetch-depth: 7

      - name: Run MegaLinter
        id: ml
        uses: oxsecurity/megalinter@v7

      - name: Archive production artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: MegaLinter reports
          path: |
            megalinter-reports
