# SPDX-FileCopyrightText: 2023 Digg - Agency for Digital Government
#
# SPDX-License-Identifier: CC0-1.0

---
name: Jitsi-moderator Workflow

on:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  pull_request:
    branches:
      - main

jobs:
  dco:
    uses: ./.github/workflows/dco.yml
  license:
    uses: ./.github/workflows/license.yml
  lint:
    uses: ./.github/workflows/lint.yml
  test:
    needs: [dco, lint]
    uses: ./.github/workflows/test.yml
  deploy:
    needs: [test]
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
